* Sravanthi WorkLog

** 16th Feb - 20th Feb 
I have learned linux course online from edx (https://www.edx.org/). Geeta mam assinged me some work regarding interviews for HTML & PHP developers . I have tested few labs from IIITH (computer programming ,physical sciences,physical chemistry).

** 22nd Feb -27th Feb
I have learned how to deploy the labs and run on the localhost. I was given a task to install and set the path for java and java 3D. Parallely i was learning linux course online frm Edx (https://www.edx.org/) too. I have learned how to deploy the labs and deployed few labs on localhost (Physical chemistry,Basic Engineering Mechanics and Strength of Materials,Physical Sciences,Hydraulics and fluid Mechanics,Electromagnetic Theory).

** 2nd Mar- 6th Mar
I have prepared a workshop feedback report which was held on 27th & 28th Feb 2015 and raised the issues on Github. Paralelly I have learned linux course online from edx .
** 9th Mar- 13th Mar
I have learned openVZ and how to run the labs over ADS. Meanwhile i have tested the labs on localhost and ADS (All the 20 labs from IIITH).

** 16th Mar -20th Mar
I was working on QA. I have tested the labs from vlab.co.in. Meanwhile i went to workshop from 17th Feb -19th Feb.

** 23rd Mar-27th Mar	
I have prepared the workshop feedback report held on 17th,18th & 19th of March and I have raised an issues on github. I was working on QA from vlab.co.in.

** 30th Mar-2nd Apr	
I was worked on QA from vlab.co.in and I was started QA on IIITH labs.

** 6th Apr-10th Apr
I have tested the labs which are being used  in the workshop held on 8th Apr. We went for workshop held on 8th Apr and done a workshop feedback report. I have tested the labs which are running on Java 3D and gave Java 3D path setup instructions link to those labs. 

** 13th Apr- 17th Apr	
I have deployed the next 7 labs and tested on the local machine.Parallely worked on QA.I have tested few labs on ADS working on Java 3D.

** 20th Apr -24th Apr
I have installed Java on centOS and done a documentation for Java Installation on CentOS. Parallely working on QA. 

** 26th Apr -30th Apr
I worked on QA for IIITH labs. I deployed the next 3 labs from 2nd set of priorotized labs. Parallely i have learned emacs editor

** 1st may to 8th may
"Continued with integration process. Done a documentation on QA. I have done separate sheets on QA for the institutes in vlab.co.in."

** 11th may to 19th may
"I have started working on QA for the next set of priorotized labs which are at level 5. I was assigned to do QA worksheet for the first set of  IIITH labs. I was started learning HTML and emacs editor."

** 18th may to 26th may
"Continued with the integration process for 2nd set of IIITH labs. Now 10 labs are at level 5. Parallely doing QA for the level 5 labs."

** 26th may to 30th may
Continued with the last week work.( Deploying labs & with QA work.) Parallely i have learned emacs editor

** 1st June & 2nd June
I have worked on deploying 2nd set of prioritized set of IIITH labs. Now 10 labs are at level 5, 3labs are at level 3, 3labs are at level2. Continued with the QA for 2nd set of IIITH labs

** 3rd June to 16th June
I was not well

** 17th June to 26th June
Working on moving all the 13 labs from level 5 to level 6. Now 13 labs are at level 5, 3labs are at level2. Continued with the QA for 2nd set of IIITH labs. I was also assigned with the work to update the syllabus list.( labs or subjects which are covered in their in their respective universities.)

** 29th June to 3rd July	
Working on moving all the 13 labs from level 5 to level 6. Now 13 labs are at level 5, 3labs are at level2. Continued with the QA for 2nd set of IIITH labs

** 6th July to 10th July	
Working on moving remaining 3 labs from level2 to level6  (2nd set of prioritised labs). Continued with the QA for 2nd set of IIITH labs

** 12th July to 17th July
Working on listing all the executable files for the first set of labs (20 labs) from iiith  and  I was worked on QA from vlab.co.in

** 20th July to 24th July	
Working on listing all the executable files for the second set of labs (20 labs) from iiith  and  I was worked on QA from vlab.co.in

** 27th July to 31st July
Working on listing all the executable files for the second set of labs (20 labs) from iiith . Worked on vlabs new landing page like updating url's of the labs.

** 3rd Aug to 7th Aug	
Worked on vlabs landing page, updated the links for the labs and created the templates for all institutes and for all the streams

** 10th Aug to 14th Aug
Met Professors regarding source files of first set of the labs. 

** 17th Aug to 21st Aug
Collected Source files for the first set (20 labs) of iiith labs and followed the integartion process for the labs having complete sources

** 24th Aug to 26th Aug
Worked on moving the first set of labs which have complete source files from level1 to level6. Out of 20 labs from first set 10 labs are having complete source files ,where 5labs are at level6, 4labs are at level4,one lab is at level2

** 28th Aug to 7th Sep
Cross check each and every lab’s source code. Push all the recover sources back to github repositories carefully. Prepare list of labs with latest detail of source code availability. Update the Makefile with respect to decompiled .java code and move the 13labs  from level1 to level6 from 1st set of labs 

** 7th Sep to 9th Sep	
"Decompilation of .class files of two labs. Two experiments of two different labs Solved errors of exp3 of computer organization lab.
Test Physical chmistry lab"

** 9Sep to 16th Sep
Collect and Document the status of all IIITH labs
	
** 7th Oct to 28th Oct
Set up Java 3D on local machine to run physical Chemistry Lab. Working on Data Structures 3rd experiment ( Flash to Js)

** 28th Oct to 4th Nov
Make a sheet with detailed info of lab’s technologies, current status and with TODO list : Corresponding technologies experiment wise .

** 4th Nov to 17th Nov	
Make a sheet with detailed info of lab’s technologies, current status and with TODO list : with Corresponding technologies experiment wise.                                                                                                            Functional test cases for new Data Structures Lab.
